version: 2
updates:
  # PlatformIO dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Mexico_City"
    reviewers:
      - "josev"  # Replace with actual maintainer usernames
    assignees:
      - "josev"  # Replace with actual maintainer usernames
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Mexico_City"
    reviewers:
      - "josev"  # Replace with actual maintainer usernames
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 3

  # Arduino/PlatformIO library dependencies would be managed through platformio.ini
  # Dependabot doesn't directly support PlatformIO, but we can create custom workflows
  # to check for library updates
