# 🎛️ Mixduino Project - Issue Templates

name: 🐛 Bug Report
description: Report a bug or issue with the Mixduino firmware
title: "[BUG] "
labels: ["🐛 bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you encountered...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Press '....'
        3. Observe '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened instead.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🎛️ Component
      description: Which component is affected?
      options:
        - MIDI Controller
        - Encoders
        - Pads
        - Potentiometers
        - LEDs
        - Hardware
        - Firmware
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📦 Firmware Version
      description: What version of the firmware are you using?
      placeholder: e.g., v2024.01.15-abc1234

  - type: textarea
    id: hardware
    attributes:
      label: 🔧 Hardware Setup
      description: Describe your hardware setup
      placeholder: |
        - Arduino model: Mega 2560
        - Additional hardware: ...
        - Connections: ...

  - type: textarea
    id: logs
    attributes:
      label: 📋 Logs/Serial Output
      description: Paste any relevant logs or serial output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.
